name: Metrics

on:
  # Run daily at midnight IST
  schedule:
    - cron: "0 0 * * *"

  # Allow manual trigger
  workflow_dispatch:

  # Run on push to main
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # ðŸ“… Isocalendar
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Unnati2603
          base: repositories
          repositories: 100
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Kolkata

      # ...existing code...
